name: 'starubiquitous kubectl cli'
description: 'GitHub Action for interacting with kubectl (k8s)'
author: 'meakawa <meakawa@icloud.com>'
branding:
  icon: 'terminal'
  color: 'blue'
inputs:
  KUBE_CONFIG:
    description: 'Kubernetes configuration'
  KUBE_HOST:
    description: 'Kubernetes cluster host (IP only, without protocol)'
  KUBE_USERNAME:
    description: 'Kubernetes cluster username'
  KUBE_PASSWORD:
    description: 'Kubernetes cluster password'
  KUBE_CERTIFICATE:
    description: 'Cluster CA certificate'
runs:
  using: 'docker'
  image: 'Dockerfile'
