name: 'starubiquitous kubectl cli'
description: 'GitHub Action for interacting with kubectl (k8s)'
author: 'meakawa <meakawa@icloud.com>'
branding:
  icon: 'terminal'
  color: 'blue'
inputs:
  args:
    description: 'Arguments for the CLI command'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
